version: '3.8'

services:
  backend:
    build:
      context: ./backend  # Path to your backend Dockerfile
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    depends_on:
      - frontend

  frontend:
    build:
      context: ./client  # Path to your frontend Dockerfile
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
